# Generated by Django 5.2.3 on 2025-07-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_boleta_total_detalleboleta_delete_boletaitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoAgua',
            new_name='Tipo',
        ),
    ]
