# Generated by Django 5.2.3 on 2025-07-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_detalleboleta_descripcioncompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='estado_entrega',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_camino', 'En camino'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
